build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
        repo: hootster/cicd_demoapp
        tag: latest
        username: hootster
        password: Bl$271339
        email: hermanchao@yahoo.com

